import Head from 'next/head'
import { Loginregister } from '../components/loginregister/loginregister'
import { Loginregisterform } from '../components/loginregisterfrom/loginregisterform'
import styles from '../styles/Home.module.scss'
import { Api } from '../utils/axios'

interface register {
  user: string;
  password: string;
}

export default function Home() {
  
  const submitregister = (e: register) => {
    Api.post('/register', {user: e.user, password: e.password}).then((response)=>{
      console.log(response)
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>To do list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Loginregister />
        <Loginregisterform title='Register' button='Register' submit={submitregister}/>
      </main>
    </div>
  )
}
