import Head from 'next/head'
import { Addtask } from '../components/addtask/addtask'
import { Logout } from '../components/logout/logout'
import { Task } from '../components/task/task'
import { Taskcomplete } from '../components/taskcomplete/taskcomplete'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>To do list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Logout />
        <div className={styles.contenttasks}>
            <div className={styles.tasks}>
                <h3>Tasks</h3>
                <Task text='TESTANDO'/>
                <Task text='TESTANDO'/>
                <Task text='TESTANDO'/>
                <Task text='TESTANDO'/>
            </div>
            <div className={styles.completetasks}>
                <h3>Tasks complete</h3>
                <Taskcomplete text='TESTANDO' />
                <Taskcomplete text='TESTANDO' />
                <Taskcomplete text='TESTANDO' />
                <Taskcomplete text='TESTANDO' />
            </div>
            <Addtask></Addtask>
        </div>
      </main>
    </div>
  )
}