import Head from 'next/head'
import { Loginregisterform } from '../components/loginregisterfrom/loginregisterform'
import styles from '../styles/Home.module.scss'
import { Api } from '../utils/axios'

interface login{
  user: string;
  password: string;
}

export default function Login() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Todo list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Julee&display=swap" rel="stylesheet"></link>
      </Head>

      <main className={styles.main}>
        <Loginregisterform type='LOGIN' description='Not a member?' link='Register' linkto='/register'></Loginregisterform>
      </main>
    </div>
  )
}
