import Head from 'next/head'
import { Task } from '../components/task/task'
import styles from '../styles/Home.module.scss'

export default function Tasks() {
  return (
    <div>
      <Head>
        <title>Todo list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Julee&display=swap" rel="stylesheet"></link>
      </Head>

      <main>
        <Task></Task>
      </main>
    </div>
  )
}