import Head from 'next/head'
import { Loginregister } from '../components/loginregister/loginregister'
import { Loginregisterform } from '../components/loginregisterfrom/loginregisterform'
import styles from '../styles/Home.module.scss'
import login from '../styles/login.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>To do list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Loginregister />
        <Loginregisterform title='Login' button='login'/>
      </main>
    </div>
  )
}
